export interface ITickets {
  situacao: string | [];
  Usuario: string;
  idprioridade: number;
  data_limit: string;
  // tempoatrasohh: number | null;
  // prazohh: number | null;
  // unidade: string;
  // datahorafim: string;
  Atividade: string;
  // DescricaoJustSuspensao: string | null;
  // idsolicitante: number;
  // data_fim: string;
  // gruponivell: string;
  OrigemAtendimento: string;
  data_solicitacao: string;
  // analise: string;
  // ICs: string | null;
  // tempoatendimentohh: number;
  nota: string;
  // DescricaoUltimaOcorrencia: string;
  idsolicitacaoservico: number;
  // situacaosla: string;
  tipoDemanda: string;
  Servico: string;
  // tempoatrasomm: number;
  // idacordonivelservico: number;
  // prazomm: number;
  // Responsavel: string;
  // Portfolio: string;
  // tempoMedioMin: number;
  GrupoAtual: string;
  // datahorasuspensao: string | null;
  Descricao: string;
  // titulosla: string;
  Contrato: string;
  // nomeprioridade: string;
  // datahorasuspensaosla: string | null;
  // horaabertura: string;
  // analisebase: string;
  // slaAtrasado: string;
  // tempoatendimentomm: number;
  // idGrupoAtual: number | null;
  showDetails: boolean;
}